#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AI_Qlearning_Black_1")]
	public partial class BlackQlearningDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertASTRATEGY(ASTRATEGY instance);
    partial void UpdateASTRATEGY(ASTRATEGY instance);
    partial void DeleteASTRATEGY(ASTRATEGY instance);
    partial void InsertVREWARD(VREWARD instance);
    partial void UpdateVREWARD(VREWARD instance);
    partial void DeleteVREWARD(VREWARD instance);
    partial void InsertQSTATE(QSTATE instance);
    partial void UpdateQSTATE(QSTATE instance);
    partial void DeleteQSTATE(QSTATE instance);
    partial void InsertSTATE(STATE instance);
    partial void UpdateSTATE(STATE instance);
    partial void DeleteSTATE(STATE instance);
    #endregion
		
		public BlackQlearningDataContext() : 
				base(global::Data.Properties.Settings.Default.AI_Qlearning_Black_1ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BlackQlearningDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlackQlearningDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlackQlearningDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BlackQlearningDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ASTRATEGY> ASTRATEGies
		{
			get
			{
				return this.GetTable<ASTRATEGY>();
			}
		}
		
		public System.Data.Linq.Table<VREWARD> VREWARDs
		{
			get
			{
				return this.GetTable<VREWARD>();
			}
		}
		
		public System.Data.Linq.Table<QSTATE> QSTATEs
		{
			get
			{
				return this.GetTable<QSTATE>();
			}
		}
		
		public System.Data.Linq.Table<STATE> STATEs
		{
			get
			{
				return this.GetTable<STATE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ASTRATEGY")]
	public partial class ASTRATEGY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ANO;
		
		private string _STRATEGY;
		
		private EntitySet<VREWARD> _VREWARDs;
		
		private EntitySet<QSTATE> _QSTATEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnANOChanging(int value);
    partial void OnANOChanged();
    partial void OnSTRATEGYChanging(string value);
    partial void OnSTRATEGYChanged();
    #endregion
		
		public ASTRATEGY()
		{
			this._VREWARDs = new EntitySet<VREWARD>(new Action<VREWARD>(this.attach_VREWARDs), new Action<VREWARD>(this.detach_VREWARDs));
			this._QSTATEs = new EntitySet<QSTATE>(new Action<QSTATE>(this.attach_QSTATEs), new Action<QSTATE>(this.detach_QSTATEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ANO
		{
			get
			{
				return this._ANO;
			}
			set
			{
				if ((this._ANO != value))
				{
					this.OnANOChanging(value);
					this.SendPropertyChanging();
					this._ANO = value;
					this.SendPropertyChanged("ANO");
					this.OnANOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STRATEGY", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string STRATEGY
		{
			get
			{
				return this._STRATEGY;
			}
			set
			{
				if ((this._STRATEGY != value))
				{
					this.OnSTRATEGYChanging(value);
					this.SendPropertyChanging();
					this._STRATEGY = value;
					this.SendPropertyChanged("STRATEGY");
					this.OnSTRATEGYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ASTRATEGY_VREWARD", Storage="_VREWARDs", ThisKey="ANO", OtherKey="ANO")]
		public EntitySet<VREWARD> VREWARDs
		{
			get
			{
				return this._VREWARDs;
			}
			set
			{
				this._VREWARDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ASTRATEGY_QSTATE", Storage="_QSTATEs", ThisKey="ANO", OtherKey="ANO")]
		public EntitySet<QSTATE> QSTATEs
		{
			get
			{
				return this._QSTATEs;
			}
			set
			{
				this._QSTATEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VREWARDs(VREWARD entity)
		{
			this.SendPropertyChanging();
			entity.ASTRATEGY = this;
		}
		
		private void detach_VREWARDs(VREWARD entity)
		{
			this.SendPropertyChanging();
			entity.ASTRATEGY = null;
		}
		
		private void attach_QSTATEs(QSTATE entity)
		{
			this.SendPropertyChanging();
			entity.ASTRATEGY = this;
		}
		
		private void detach_QSTATEs(QSTATE entity)
		{
			this.SendPropertyChanging();
			entity.ASTRATEGY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VREWARD")]
	public partial class VREWARD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SNO;
		
		private int _ANO;
		
		private int _TIMES;
		
		private double _REWARD;
		
		private int _TOTAL;
		
		private EntityRef<ASTRATEGY> _ASTRATEGY;
		
		private EntityRef<STATE> _STATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSNOChanging(int value);
    partial void OnSNOChanged();
    partial void OnANOChanging(int value);
    partial void OnANOChanged();
    partial void OnTIMESChanging(int value);
    partial void OnTIMESChanged();
    partial void OnREWARDChanging(double value);
    partial void OnREWARDChanged();
    partial void OnTOTALChanging(int value);
    partial void OnTOTALChanged();
    #endregion
		
		public VREWARD()
		{
			this._ASTRATEGY = default(EntityRef<ASTRATEGY>);
			this._STATE = default(EntityRef<STATE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					if (this._STATE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSNOChanging(value);
					this.SendPropertyChanging();
					this._SNO = value;
					this.SendPropertyChanged("SNO");
					this.OnSNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ANO
		{
			get
			{
				return this._ANO;
			}
			set
			{
				if ((this._ANO != value))
				{
					if (this._ASTRATEGY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnANOChanging(value);
					this.SendPropertyChanging();
					this._ANO = value;
					this.SendPropertyChanged("ANO");
					this.OnANOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIMES", DbType="Int NOT NULL")]
		public int TIMES
		{
			get
			{
				return this._TIMES;
			}
			set
			{
				if ((this._TIMES != value))
				{
					this.OnTIMESChanging(value);
					this.SendPropertyChanging();
					this._TIMES = value;
					this.SendPropertyChanged("TIMES");
					this.OnTIMESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REWARD", DbType="Float NOT NULL")]
		public double REWARD
		{
			get
			{
				return this._REWARD;
			}
			set
			{
				if ((this._REWARD != value))
				{
					this.OnREWARDChanging(value);
					this.SendPropertyChanging();
					this._REWARD = value;
					this.SendPropertyChanged("REWARD");
					this.OnREWARDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL", DbType="Int NOT NULL")]
		public int TOTAL
		{
			get
			{
				return this._TOTAL;
			}
			set
			{
				if ((this._TOTAL != value))
				{
					this.OnTOTALChanging(value);
					this.SendPropertyChanging();
					this._TOTAL = value;
					this.SendPropertyChanged("TOTAL");
					this.OnTOTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ASTRATEGY_VREWARD", Storage="_ASTRATEGY", ThisKey="ANO", OtherKey="ANO", IsForeignKey=true)]
		public ASTRATEGY ASTRATEGY
		{
			get
			{
				return this._ASTRATEGY.Entity;
			}
			set
			{
				ASTRATEGY previousValue = this._ASTRATEGY.Entity;
				if (((previousValue != value) 
							|| (this._ASTRATEGY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ASTRATEGY.Entity = null;
						previousValue.VREWARDs.Remove(this);
					}
					this._ASTRATEGY.Entity = value;
					if ((value != null))
					{
						value.VREWARDs.Add(this);
						this._ANO = value.ANO;
					}
					else
					{
						this._ANO = default(int);
					}
					this.SendPropertyChanged("ASTRATEGY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STATE_VREWARD", Storage="_STATE", ThisKey="SNO", OtherKey="SNO", IsForeignKey=true)]
		public STATE STATE
		{
			get
			{
				return this._STATE.Entity;
			}
			set
			{
				STATE previousValue = this._STATE.Entity;
				if (((previousValue != value) 
							|| (this._STATE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STATE.Entity = null;
						previousValue.VREWARDs.Remove(this);
					}
					this._STATE.Entity = value;
					if ((value != null))
					{
						value.VREWARDs.Add(this);
						this._SNO = value.SNO;
					}
					else
					{
						this._SNO = default(int);
					}
					this.SendPropertyChanged("STATE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QSTATE")]
	public partial class QSTATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SNO;
		
		private int _ANO;
		
		private double _VALUE;
		
		private EntityRef<ASTRATEGY> _ASTRATEGY;
		
		private EntityRef<STATE> _STATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSNOChanging(int value);
    partial void OnSNOChanged();
    partial void OnANOChanging(int value);
    partial void OnANOChanged();
    partial void OnVALUEChanging(double value);
    partial void OnVALUEChanged();
    #endregion
		
		public QSTATE()
		{
			this._ASTRATEGY = default(EntityRef<ASTRATEGY>);
			this._STATE = default(EntityRef<STATE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					if (this._STATE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSNOChanging(value);
					this.SendPropertyChanging();
					this._SNO = value;
					this.SendPropertyChanged("SNO");
					this.OnSNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ANO
		{
			get
			{
				return this._ANO;
			}
			set
			{
				if ((this._ANO != value))
				{
					if (this._ASTRATEGY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnANOChanging(value);
					this.SendPropertyChanging();
					this._ANO = value;
					this.SendPropertyChanged("ANO");
					this.OnANOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALUE", DbType="Float NOT NULL")]
		public double VALUE
		{
			get
			{
				return this._VALUE;
			}
			set
			{
				if ((this._VALUE != value))
				{
					this.OnVALUEChanging(value);
					this.SendPropertyChanging();
					this._VALUE = value;
					this.SendPropertyChanged("VALUE");
					this.OnVALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ASTRATEGY_QSTATE", Storage="_ASTRATEGY", ThisKey="ANO", OtherKey="ANO", IsForeignKey=true)]
		public ASTRATEGY ASTRATEGY
		{
			get
			{
				return this._ASTRATEGY.Entity;
			}
			set
			{
				ASTRATEGY previousValue = this._ASTRATEGY.Entity;
				if (((previousValue != value) 
							|| (this._ASTRATEGY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ASTRATEGY.Entity = null;
						previousValue.QSTATEs.Remove(this);
					}
					this._ASTRATEGY.Entity = value;
					if ((value != null))
					{
						value.QSTATEs.Add(this);
						this._ANO = value.ANO;
					}
					else
					{
						this._ANO = default(int);
					}
					this.SendPropertyChanged("ASTRATEGY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STATE_QSTATE", Storage="_STATE", ThisKey="SNO", OtherKey="SNO", IsForeignKey=true)]
		public STATE STATE
		{
			get
			{
				return this._STATE.Entity;
			}
			set
			{
				STATE previousValue = this._STATE.Entity;
				if (((previousValue != value) 
							|| (this._STATE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STATE.Entity = null;
						previousValue.QSTATEs.Remove(this);
					}
					this._STATE.Entity = value;
					if ((value != null))
					{
						value.QSTATEs.Add(this);
						this._SNO = value.SNO;
					}
					else
					{
						this._SNO = default(int);
					}
					this.SendPropertyChanged("STATE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STATE")]
	public partial class STATE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SNO;
		
		private string _MSTATE;
		
		private EntitySet<VREWARD> _VREWARDs;
		
		private EntitySet<QSTATE> _QSTATEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSNOChanging(int value);
    partial void OnSNOChanged();
    partial void OnMSTATEChanging(string value);
    partial void OnMSTATEChanged();
    #endregion
		
		public STATE()
		{
			this._VREWARDs = new EntitySet<VREWARD>(new Action<VREWARD>(this.attach_VREWARDs), new Action<VREWARD>(this.detach_VREWARDs));
			this._QSTATEs = new EntitySet<QSTATE>(new Action<QSTATE>(this.attach_QSTATEs), new Action<QSTATE>(this.detach_QSTATEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this.OnSNOChanging(value);
					this.SendPropertyChanging();
					this._SNO = value;
					this.SendPropertyChanged("SNO");
					this.OnSNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSTATE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MSTATE
		{
			get
			{
				return this._MSTATE;
			}
			set
			{
				if ((this._MSTATE != value))
				{
					this.OnMSTATEChanging(value);
					this.SendPropertyChanging();
					this._MSTATE = value;
					this.SendPropertyChanged("MSTATE");
					this.OnMSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STATE_VREWARD", Storage="_VREWARDs", ThisKey="SNO", OtherKey="SNO")]
		public EntitySet<VREWARD> VREWARDs
		{
			get
			{
				return this._VREWARDs;
			}
			set
			{
				this._VREWARDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STATE_QSTATE", Storage="_QSTATEs", ThisKey="SNO", OtherKey="SNO")]
		public EntitySet<QSTATE> QSTATEs
		{
			get
			{
				return this._QSTATEs;
			}
			set
			{
				this._QSTATEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_VREWARDs(VREWARD entity)
		{
			this.SendPropertyChanging();
			entity.STATE = this;
		}
		
		private void detach_VREWARDs(VREWARD entity)
		{
			this.SendPropertyChanging();
			entity.STATE = null;
		}
		
		private void attach_QSTATEs(QSTATE entity)
		{
			this.SendPropertyChanging();
			entity.STATE = this;
		}
		
		private void detach_QSTATEs(QSTATE entity)
		{
			this.SendPropertyChanging();
			entity.STATE = null;
		}
	}
}
#pragma warning restore 1591
